### ISSUE TITLE
Some information about the variables in the code

### ISSUE THREAD

**Issue by hoomegic** [liangzid/LoRD-MEA#1]
There are many versions of the LoRD method in the ‘lord_train.py’, such as LoRD-III, LoRD-IV, LoRD-V, etc. What are the differences between these different versions? In addition, the vanilla method is not reflected in the paper. What is this method?

**Comment by liangzid** [comment]
They are different loss functions we have tested. You can use `LoRD-VI`, which can be seen as the final version of LoRD. `vanilla` denotes the `MLE` in the paper.

Thanks for your feedback. We will clean our repository recently~
